apiVersion: v1
kind: Service
metadata:
  name: {{ include "drawio.fullname" . }}
  labels:
    {{- include "drawio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  ports:
    - name: http
      port: {{ .Values.service.ports[0].port }}
  selector:
    {{- include "drawio.selectorLabels" . | nindent 4 }}